# File @generated by alxse student/authors.c DO NOT EDIT
# this file lists all contributors to the repository
# See simple_shell/authors to make modifications

  Roseline Igwe <dr.roxiecrux@gmail.com>
 
  Nnenna Uzoezie <nnennauzo55@gmail.com>
